### ISSUE TITLE
Bricked device

### ISSUE THREAD

**Issue by AlexFRAN** [itsarjunsinh/elder_launcher#16]
I've installed it on a phone from an old lady and set it as default launcher (yesterday everything worked fine). (The phone is from a brand called: TCL).
Returned a day later to see how it turned out and the only thing that i saw, was stuck in the bootloader (screenshot attached).
Could this have been connected to the launcher (its the only thing i installed, i didn't root it, idk if she did anything other than that in the meantime).

![bricked_phone](https://user-images.githubusercontent.com/10141409/138651700-618c2b4c-fb70-498f-bcbf-7317078b1cf8.jpg)
.

**Comment by itsarjunsinh** [comment]
Hello Alex, I've looked into it and there have been no crashes registered on any TCL devices. There also have been no similar reports, so I'm going to close this as unrelated to the app and device/manufacturer related issue.

P.S. I'll be releasing the update with Italian translation you submitted sometime soon.
