### ISSUE TITLE
How to contribute to add new language

### ISSUE THREAD

**Issue by ngoctuan42** [itsarjunsinh/elder_launcher#28]
I want to add new language for app. Please show me the way to contribute.

**Comment by itsarjunsinh** [comment]
Hi @ngoctuan42, thanks for your interest.

You may create a new translation file in this folder [lib/l10n](https://github.com/itsarjunsinh/elder_launcher/tree/master/lib/l10n).

The file name should be **intl_[language code].arb**.
Please refer to the other files for the overall format and string key names.
