### ISSUE TITLE
App list not updating after install/uninstall

### ISSUE THREAD

**Issue by sparkdesign2000** [itsarjunsinh/elder_launcher#8]
Hi my uncle noticed that app list is never updating when you install or uninstall apps

It takes 10-15 min

**Comment by itsarjunsinh** [comment]
This is a known issue. The Flutter plugins that Elder Launcher uses to load app and contact list don't notify on additions and removals. So, Elder Launcher reloads app list every 5 minutes and contacts every 10 minutes.

**Current solution:** Do manual reload from the edit menu (pencil icon). It contains "Reload App List" and "Reload Contact List" buttons.

In future, I'll write a native plugin to solve this issue.

**Comment by itsarjunsinh** [comment]
I intend on keeping this issue open until I fix this. Thanks for bringing this to my attention.

**Comment by itsarjunsinh** [comment]
This is fixed in #11. Changes will be in v1.4 of the app.
